import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TanstackProvider from '@/providers/tanstack.provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Poke Feed',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanstackProvider>
                    <main>{children}</main>
                </TanstackProvider>
            </body>
        </html>
    )
}
